<?php
/** @var $this SchumacherFM_OpCachePanel_Block_Adminhtml_Graph */

?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Graph') ?></h4>
    </div>
    <div id="opcache_memory" class="opPie"></div>
    <div id="opcache_keys" class="opPie"></div>
    <div id="opcache_hits" class="opPie"></div>
    <div id="opcache_restarts" class="opPie"></div>

<!--    --><?php //echo $this->getGraphsDisplay(); ?>
</div>

