<?php
/** @var $this SchumacherFM_OpCachePanel_Block_Adminhtml_Panel */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getTitle() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getRecheckButton() ?>
                <?php echo $this->getResetButton() ?>
                <?php echo $this->getCompileButton() ?>
            </td>
        </tr>
    </table>
</div>

<?php
echo $this->getChildHtml('opcache_infodata');
?>

<div class="content-header" style="clear:both;">
    <a target="_blank" href="http://files.zend.com/help/Zend-Server-6/content/zendoptimizerplus.html">directives guide</a> |
    <a target="_blank" href="http://files.zend.com/help/Zend-Server-6/content/zend_optimizer+_-_php_api.htm">functions guide</a> |
    <a target="_blank" href="https://wiki.php.net/rfc/optimizerplus">wiki.php.net</a> |
    <a target="_blank" href="http://pecl.php.net/package/ZendOpcache">pecl</a> |
    <a target="_blank" href="https://github.com/zend-dev/ZendOptimizerPlus/">Zend source</a>
</div>
<script>
    function confirmedCacheAction(url) {
        if (confirm('Are you sure?')) {
            window.location.href = url;
        }
    }
</script>